// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gateway

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClientTravelCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsClientTravelCmd(buf []byte, offset flatbuffers.UOffsetT) *ClientTravelCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClientTravelCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishClientTravelCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsClientTravelCmd(buf []byte, offset flatbuffers.UOffsetT) *ClientTravelCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ClientTravelCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedClientTravelCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ClientTravelCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClientTravelCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ClientTravelCmd) LoginObjId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClientTravelCmd) MutateLoginObjId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *ClientTravelCmd) Uid() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientTravelCmd) Unk2() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClientTravelCmd) MutateUnk2(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *ClientTravelCmd) ActorTag() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientTravelCmd) ServerAddr() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientTravelCmd) Location() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientTravelCmd) Unk3() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClientTravelCmd) MutateUnk3(n int32) bool {
	return rcv._tab.MutateInt32Slot(16, n)
}

func (rcv *ClientTravelCmd) RoleId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClientTravelCmd) MutateRoleId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(18, n)
}

func (rcv *ClientTravelCmd) CharacterBp() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientTravelCmd) Unk4() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClientTravelCmd) MutateUnk4(n int32) bool {
	return rcv._tab.MutateInt32Slot(22, n)
}

func (rcv *ClientTravelCmd) Unk5() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClientTravelCmd) MutateUnk5(n int32) bool {
	return rcv._tab.MutateInt32Slot(24, n)
}

func (rcv *ClientTravelCmd) Unk6() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClientTravelCmd) MutateUnk6(n int32) bool {
	return rcv._tab.MutateInt32Slot(26, n)
}

func (rcv *ClientTravelCmd) Unk7() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClientTravelCmd) MutateUnk7(n int32) bool {
	return rcv._tab.MutateInt32Slot(28, n)
}

func ClientTravelCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(13)
}
func ClientTravelCmdAddLoginObjId(builder *flatbuffers.Builder, loginObjId uint64) {
	builder.PrependUint64Slot(0, loginObjId, 0)
}
func ClientTravelCmdAddUid(builder *flatbuffers.Builder, uid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(uid), 0)
}
func ClientTravelCmdAddUnk2(builder *flatbuffers.Builder, unk2 int32) {
	builder.PrependInt32Slot(2, unk2, 0)
}
func ClientTravelCmdAddActorTag(builder *flatbuffers.Builder, actorTag flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(actorTag), 0)
}
func ClientTravelCmdAddServerAddr(builder *flatbuffers.Builder, serverAddr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(serverAddr), 0)
}
func ClientTravelCmdAddLocation(builder *flatbuffers.Builder, location flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(location), 0)
}
func ClientTravelCmdAddUnk3(builder *flatbuffers.Builder, unk3 int32) {
	builder.PrependInt32Slot(6, unk3, 0)
}
func ClientTravelCmdAddRoleId(builder *flatbuffers.Builder, roleId uint64) {
	builder.PrependUint64Slot(7, roleId, 0)
}
func ClientTravelCmdAddCharacterBp(builder *flatbuffers.Builder, characterBp flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(characterBp), 0)
}
func ClientTravelCmdAddUnk4(builder *flatbuffers.Builder, unk4 int32) {
	builder.PrependInt32Slot(9, unk4, 0)
}
func ClientTravelCmdAddUnk5(builder *flatbuffers.Builder, unk5 int32) {
	builder.PrependInt32Slot(10, unk5, 0)
}
func ClientTravelCmdAddUnk6(builder *flatbuffers.Builder, unk6 int32) {
	builder.PrependInt32Slot(11, unk6, 0)
}
func ClientTravelCmdAddUnk7(builder *flatbuffers.Builder, unk7 int32) {
	builder.PrependInt32Slot(12, unk7, 0)
}
func ClientTravelCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
