// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gateway

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClientKeepAliveCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsClientKeepAliveCmd(buf []byte, offset flatbuffers.UOffsetT) *ClientKeepAliveCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClientKeepAliveCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishClientKeepAliveCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsClientKeepAliveCmd(buf []byte, offset flatbuffers.UOffsetT) *ClientKeepAliveCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ClientKeepAliveCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedClientKeepAliveCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ClientKeepAliveCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClientKeepAliveCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ClientKeepAliveCmd) ClientTick() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClientKeepAliveCmd) MutateClientTick(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func ClientKeepAliveCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ClientKeepAliveCmdAddClientTick(builder *flatbuffers.Builder, clientTick uint32) {
	builder.PrependUint32Slot(0, clientTick, 0)
}
func ClientKeepAliveCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
