// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gateway

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClientLoginReq struct {
	_tab flatbuffers.Table
}

func GetRootAsClientLoginReq(buf []byte, offset flatbuffers.UOffsetT) *ClientLoginReq {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClientLoginReq{}
	x.Init(buf, n+offset)
	return x
}

func FinishClientLoginReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsClientLoginReq(buf []byte, offset flatbuffers.UOffsetT) *ClientLoginReq {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ClientLoginReq{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedClientLoginReqBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ClientLoginReq) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClientLoginReq) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ClientLoginReq) ClientVersion() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientLoginReq) Username() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientLoginReq) Password() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientLoginReq) LoginType() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClientLoginReq) MutateLoginType(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *ClientLoginReq) Unk1() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientLoginReq) GameId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientLoginReq) ChannelId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientLoginReq) NoticeChannel() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientLoginReq) Unk2() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientLoginReq) ClientWanIp() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientLoginReq) DeviceId1() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientLoginReq) DeviceId2() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientLoginReq) DeviceModel() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientLoginReq) OsVersion() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientLoginReq) Memory() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClientLoginReq) MutateMemory(n int32) bool {
	return rcv._tab.MutateInt32Slot(32, n)
}

func (rcv *ClientLoginReq) OsType() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClientLoginReq) MutateOsType(n int32) bool {
	return rcv._tab.MutateInt32Slot(34, n)
}

func (rcv *ClientLoginReq) Unk5() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClientLoginReq) MutateUnk5(n int32) bool {
	return rcv._tab.MutateInt32Slot(36, n)
}

func (rcv *ClientLoginReq) Unk6() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ClientLoginReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(18)
}
func ClientLoginReqAddClientVersion(builder *flatbuffers.Builder, clientVersion flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(clientVersion), 0)
}
func ClientLoginReqAddUsername(builder *flatbuffers.Builder, username flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(username), 0)
}
func ClientLoginReqAddPassword(builder *flatbuffers.Builder, password flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(password), 0)
}
func ClientLoginReqAddLoginType(builder *flatbuffers.Builder, loginType int32) {
	builder.PrependInt32Slot(3, loginType, 0)
}
func ClientLoginReqAddUnk1(builder *flatbuffers.Builder, unk1 flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(unk1), 0)
}
func ClientLoginReqAddGameId(builder *flatbuffers.Builder, gameId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(gameId), 0)
}
func ClientLoginReqAddChannelId(builder *flatbuffers.Builder, channelId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(channelId), 0)
}
func ClientLoginReqAddNoticeChannel(builder *flatbuffers.Builder, noticeChannel flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(noticeChannel), 0)
}
func ClientLoginReqAddUnk2(builder *flatbuffers.Builder, unk2 flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(unk2), 0)
}
func ClientLoginReqAddClientWanIp(builder *flatbuffers.Builder, clientWanIp flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(clientWanIp), 0)
}
func ClientLoginReqAddDeviceId1(builder *flatbuffers.Builder, deviceId1 flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(deviceId1), 0)
}
func ClientLoginReqAddDeviceId2(builder *flatbuffers.Builder, deviceId2 flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(deviceId2), 0)
}
func ClientLoginReqAddDeviceModel(builder *flatbuffers.Builder, deviceModel flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(12, flatbuffers.UOffsetT(deviceModel), 0)
}
func ClientLoginReqAddOsVersion(builder *flatbuffers.Builder, osVersion flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(13, flatbuffers.UOffsetT(osVersion), 0)
}
func ClientLoginReqAddMemory(builder *flatbuffers.Builder, memory int32) {
	builder.PrependInt32Slot(14, memory, 0)
}
func ClientLoginReqAddOsType(builder *flatbuffers.Builder, osType int32) {
	builder.PrependInt32Slot(15, osType, 0)
}
func ClientLoginReqAddUnk5(builder *flatbuffers.Builder, unk5 int32) {
	builder.PrependInt32Slot(16, unk5, 0)
}
func ClientLoginReqAddUnk6(builder *flatbuffers.Builder, unk6 flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(17, flatbuffers.UOffsetT(unk6), 0)
}
func ClientLoginReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
