// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gateway

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ServerErrorMsgCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsServerErrorMsgCmd(buf []byte, offset flatbuffers.UOffsetT) *ServerErrorMsgCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ServerErrorMsgCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishServerErrorMsgCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsServerErrorMsgCmd(buf []byte, offset flatbuffers.UOffsetT) *ServerErrorMsgCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ServerErrorMsgCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedServerErrorMsgCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ServerErrorMsgCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ServerErrorMsgCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ServerErrorMsgCmd) ErrorMsg() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ServerErrorMsgCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ServerErrorMsgCmdAddErrorMsg(builder *flatbuffers.Builder, errorMsg flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(errorMsg), 0)
}
func ServerErrorMsgCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
