// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gateway

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ServerVersionCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsServerVersionCmd(buf []byte, offset flatbuffers.UOffsetT) *ServerVersionCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ServerVersionCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishServerVersionCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsServerVersionCmd(buf []byte, offset flatbuffers.UOffsetT) *ServerVersionCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ServerVersionCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedServerVersionCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ServerVersionCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ServerVersionCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ServerVersionCmd) ServerVersion() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ServerVersionCmd) ClientWanIp() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ServerVersionCmd) ClientWanPort() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ServerVersionCmd) MutateClientWanPort(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *ServerVersionCmd) HeartType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ServerVersionCmd) MutateHeartType(n byte) bool {
	return rcv._tab.MutateByteSlot(10, n)
}

func (rcv *ServerVersionCmd) HeartClientInterval() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ServerVersionCmd) MutateHeartClientInterval(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func (rcv *ServerVersionCmd) CheckServerInterval() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ServerVersionCmd) MutateCheckServerInterval(n int32) bool {
	return rcv._tab.MutateInt32Slot(14, n)
}

func (rcv *ServerVersionCmd) ServerId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ServerVersionCmd) MutateServerId(n int32) bool {
	return rcv._tab.MutateInt32Slot(16, n)
}

func (rcv *ServerVersionCmd) ServerTimeUtc() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ServerVersionCmd) MutateServerTimeUtc(n int64) bool {
	return rcv._tab.MutateInt64Slot(18, n)
}

func (rcv *ServerVersionCmd) ServerTime() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ServerVersionCmd) MutateServerTime(n int64) bool {
	return rcv._tab.MutateInt64Slot(20, n)
}

func (rcv *ServerVersionCmd) Unk1(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ServerVersionCmd) Unk1Length() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ServerVersionCmd) Unk1Bytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ServerVersionCmd) MutateUnk1(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ServerVersionCmd) Unk2(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ServerVersionCmd) Unk2Length() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ServerVersionCmd) Unk2Bytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ServerVersionCmd) MutateUnk2(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func ServerVersionCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(11)
}
func ServerVersionCmdAddServerVersion(builder *flatbuffers.Builder, serverVersion flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(serverVersion), 0)
}
func ServerVersionCmdAddClientWanIp(builder *flatbuffers.Builder, clientWanIp flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(clientWanIp), 0)
}
func ServerVersionCmdAddClientWanPort(builder *flatbuffers.Builder, clientWanPort int32) {
	builder.PrependInt32Slot(2, clientWanPort, 0)
}
func ServerVersionCmdAddHeartType(builder *flatbuffers.Builder, heartType byte) {
	builder.PrependByteSlot(3, heartType, 0)
}
func ServerVersionCmdAddHeartClientInterval(builder *flatbuffers.Builder, heartClientInterval int32) {
	builder.PrependInt32Slot(4, heartClientInterval, 0)
}
func ServerVersionCmdAddCheckServerInterval(builder *flatbuffers.Builder, checkServerInterval int32) {
	builder.PrependInt32Slot(5, checkServerInterval, 0)
}
func ServerVersionCmdAddServerId(builder *flatbuffers.Builder, serverId int32) {
	builder.PrependInt32Slot(6, serverId, 0)
}
func ServerVersionCmdAddServerTimeUtc(builder *flatbuffers.Builder, serverTimeUtc int64) {
	builder.PrependInt64Slot(7, serverTimeUtc, 0)
}
func ServerVersionCmdAddServerTime(builder *flatbuffers.Builder, serverTime int64) {
	builder.PrependInt64Slot(8, serverTime, 0)
}
func ServerVersionCmdAddUnk1(builder *flatbuffers.Builder, unk1 flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(unk1), 0)
}
func ServerVersionCmdStartUnk1Vector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ServerVersionCmdAddUnk2(builder *flatbuffers.Builder, unk2 flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(unk2), 0)
}
func ServerVersionCmdStartUnk2Vector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ServerVersionCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
