// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package gateway

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ServerKeepAliveCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsServerKeepAliveCmd(buf []byte, offset flatbuffers.UOffsetT) *ServerKeepAliveCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ServerKeepAliveCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishServerKeepAliveCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsServerKeepAliveCmd(buf []byte, offset flatbuffers.UOffsetT) *ServerKeepAliveCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ServerKeepAliveCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedServerKeepAliveCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ServerKeepAliveCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ServerKeepAliveCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ServerKeepAliveCmd) Unk1() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ServerKeepAliveCmd) MutateUnk1(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *ServerKeepAliveCmd) ServerTimeUtc() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ServerKeepAliveCmd) MutateServerTimeUtc(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *ServerKeepAliveCmd) ServerTime() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ServerKeepAliveCmd) MutateServerTime(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func ServerKeepAliveCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ServerKeepAliveCmdAddUnk1(builder *flatbuffers.Builder, unk1 uint32) {
	builder.PrependUint32Slot(0, unk1, 0)
}
func ServerKeepAliveCmdAddServerTimeUtc(builder *flatbuffers.Builder, serverTimeUtc int64) {
	builder.PrependInt64Slot(1, serverTimeUtc, 0)
}
func ServerKeepAliveCmdAddServerTime(builder *flatbuffers.Builder, serverTime int64) {
	builder.PrependInt64Slot(2, serverTime, 0)
}
func ServerKeepAliveCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
