// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package packet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PacketHead struct {
	_tab flatbuffers.Table
}

func GetRootAsPacketHead(buf []byte, offset flatbuffers.UOffsetT) *PacketHead {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PacketHead{}
	x.Init(buf, n+offset)
	return x
}

func FinishPacketHeadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPacketHead(buf []byte, offset flatbuffers.UOffsetT) *PacketHead {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PacketHead{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPacketHeadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PacketHead) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PacketHead) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PacketHead) MessageId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PacketHead) MutateMessageId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *PacketHead) HeaderLen() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PacketHead) MutateHeaderLen(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *PacketHead) PayloadLen() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PacketHead) MutatePayloadLen(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func PacketHeadStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func PacketHeadAddMessageId(builder *flatbuffers.Builder, messageId int32) {
	builder.PrependInt32Slot(0, messageId, 0)
}
func PacketHeadAddHeaderLen(builder *flatbuffers.Builder, headerLen int32) {
	builder.PrependInt32Slot(1, headerLen, 0)
}
func PacketHeadAddPayloadLen(builder *flatbuffers.Builder, payloadLen int32) {
	builder.PrependInt32Slot(2, payloadLen, 0)
}
func PacketHeadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
