// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package packet

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PacketHead struct {
	_tab flatbuffers.Table
}

func GetRootAsPacketHead(buf []byte, offset flatbuffers.UOffsetT) *PacketHead {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PacketHead{}
	x.Init(buf, n+offset)
	return x
}

func FinishPacketHeadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPacketHead(buf []byte, offset flatbuffers.UOffsetT) *PacketHead {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PacketHead{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPacketHeadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PacketHead) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PacketHead) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PacketHead) MsgCode() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PacketHead) MutateMsgCode(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *PacketHead) ErrorCode() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PacketHead) MutateErrorCode(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *PacketHead) MsgSize() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PacketHead) MutateMsgSize(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func PacketHeadStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func PacketHeadAddMsgCode(builder *flatbuffers.Builder, msgCode int32) {
	builder.PrependInt32Slot(0, msgCode, 0)
}
func PacketHeadAddErrorCode(builder *flatbuffers.Builder, errorCode int32) {
	builder.PrependInt32Slot(1, errorCode, 0)
}
func PacketHeadAddMsgSize(builder *flatbuffers.Builder, msgSize int32) {
	builder.PrependInt32Slot(2, msgSize, 0)
}
func PacketHeadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
