// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package game

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GameDataFirstSync struct {
	_tab flatbuffers.Table
}

func GetRootAsGameDataFirstSync(buf []byte, offset flatbuffers.UOffsetT) *GameDataFirstSync {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GameDataFirstSync{}
	x.Init(buf, n+offset)
	return x
}

func FinishGameDataFirstSyncBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGameDataFirstSync(buf []byte, offset flatbuffers.UOffsetT) *GameDataFirstSync {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GameDataFirstSync{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGameDataFirstSyncBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GameDataFirstSync) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GameDataFirstSync) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GameDataFirstSync) RoleId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GameDataFirstSync) MutateRoleId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *GameDataFirstSync) Unk1() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GameDataFirstSync) MutateUnk1(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func GameDataFirstSyncStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GameDataFirstSyncAddRoleId(builder *flatbuffers.Builder, roleId uint64) {
	builder.PrependUint64Slot(0, roleId, 0)
}
func GameDataFirstSyncAddUnk1(builder *flatbuffers.Builder, unk1 int32) {
	builder.PrependInt32Slot(1, unk1, 0)
}
func GameDataFirstSyncEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
