// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package player_mgr

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UpdateReconnectToken struct {
	_tab flatbuffers.Table
}

func GetRootAsUpdateReconnectToken(buf []byte, offset flatbuffers.UOffsetT) *UpdateReconnectToken {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UpdateReconnectToken{}
	x.Init(buf, n+offset)
	return x
}

func FinishUpdateReconnectTokenBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUpdateReconnectToken(buf []byte, offset flatbuffers.UOffsetT) *UpdateReconnectToken {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UpdateReconnectToken{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUpdateReconnectTokenBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UpdateReconnectToken) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UpdateReconnectToken) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UpdateReconnectToken) ReconnectToken() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func UpdateReconnectTokenStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func UpdateReconnectTokenAddReconnectToken(builder *flatbuffers.Builder, reconnectToken flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(reconnectToken), 0)
}
func UpdateReconnectTokenEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
